## In this R script, I write two functions to cache the operation of getting 
##the inverse of a matrix, a time-computing operation when a matrix is very large

## The first functions takes as input argument a squared matrix and creates a spetial matrix 
##The spetial matrix is a list of 4 functions which: 
#1. Set the matrix (set)
#2. Get the matrix value (get)
#3. Set the inverse of the matrix (setinv)
#4. Get the value of the inversed matrix (getinv)

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinv <- function(solve) m <<- solve
  getinv <- function() m
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}

## The second function "cacheSolve" takes as input a spetial matrix generated by the previous function
##This function get the value of a matrix and search for this matrix in the cache
##If the matrix is already in the cache, yields the previously calculated inversed matrix
##If the matrix is not found in the cache, then the function return the inverse of the matrix 
## and the inversed matrix is then stored in the cache

cacheSolve <- function(x, ...) {
  m <- x$getinv()
  if(!is.null(m)) {
    message("getting cached matrix")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinv(m)
  m
}
